Add linting logic for prowjobs
aws/eks-distro-prow-jobs pull request #53
Opened 2020-12-24 23:26 UTC by abhay-krishna

Adding linting presubmit and script for prowjobs. When a PR is raised to add new jobs or change existing jobs, the script runs checks to determine if the added jobs have the proper configuration of buckets, clusters, service accounts, `make` targets, `always_run` and `skip_report` flags, resource requirements, etc. These checks are separate for presubmits and postsubmits. The script also counts the errors for each kind of job and provides the necessary fixes that need to be made. 

This presubmit will be an additional validation test for the jobs we add to the prowjobs repo, i.e., it will catch the common errors like incorrect bucketname/cluster for the job type, which a human reviewer may miss when reviewing.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-24 23:51 UTC, abhay-krishna commented
/hold

2020-12-26 19:48 UTC, micahhausler requested changes
This is a great start!

2020-12-26 19:48 UTC, micahhausler commented on scripts/lint_jobs.sh
> +set -e
I think this test is great, I'd suggest implementing it in Go so you can use the same [parsing](https://github.com/kubernetes/test-infra/blob/59e70a3d6443f37ba94961c9cef567655431bc20/prow/config/config.go#L1091) and [types](https://pkg.go.dev/k8s.io/test-infra/prow/config#JobConfig) as Prow for more advanced (and testable) checks in the future.

I'd also be great to run [`checkconfig`](https://github.com/kubernetes/test-infra/tree/2abb7ff26579325f6a335990003f665755c96d7a/prow/cmd/checkconfig) before this test for basic schema validation as well

2021-01-06 00:06 UTC, vivek-koppuru approved these changes
/lgtm
/approve

2021-01-06 00:08 UTC, abhay-krishna commented
/unhold

2021-01-06 00:09 UTC, merged